"""
Django settings for mykmitl_planner project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from pyexpat.errors import messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kr2a(7rw6gsbp&)(zy44uqics*g(xev*t72my*ug%p^a-tz1jz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.humanize",
    

     # แอปของ allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.mfa',
    'tailwind',
    'theme',
    'django_browser_reload',
    
    'widget_tweaks',
    
    'planner',
    'bookings',
    'chat',
    'authen'
]
TAILWIND_APP_NAME = 'theme'
SITE_ID = 1 

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Authentication middleware
    'allauth.account.middleware.AccountMiddleware',  # Add this line
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mykmitl_planner.urls'

NPM_BIN_PATH = '/usr/local/bin/npm'



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'authen', 'templates'),
            os.path.join(BASE_DIR, 'chat', 'templates'),
            os.path.join(BASE_DIR, 'bookings', 'templates'),
            os.path.join(BASE_DIR, 'planner', 'templates')
        ],
        'APP_DIRS': True,  # ให้ Django ค้นหาเทมเพลตจากโฟลเดอร์ 'templates' ของแอปใน INSTALLED_APPS
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'mykmitl_planner.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
       "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "mykmitl", 
        "USER":  "postgres",
        "PASSWORD": "6743",
        "HOST": "localhost",
        "PORT": "8000",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'


STATICFILES_DIRS = [
            os.path.join(BASE_DIR, 'authen', 'static'),
            os.path.join(BASE_DIR, 'chat', 'static'),
            os.path.join(BASE_DIR, 'bookings', 'static'),
            os.path.join(BASE_DIR, 'planner', 'static')
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ตั้งค่า authentication backends สำหรับ allauth
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # การยืนยันตัวตนแบบปกติ
    'allauth.account.auth_backends.AuthenticationBackend',  # สำหรับ allauth
)

# เพิ่มเติมการตั้งค่าสำหรับ allauth
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # บังคับให้ผู้ใช้ยืนยันอีเมล
ACCOUNT_EMAIL_REQUIRED = True  # จำเป็นต้องใช้อีเมลในการสมัคร

