# Generated by Django 5.1.1 on 2024-09-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
