# Generated by Django 5.0.6 on 2024-09-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_student_email_alter_student_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_pics/'),
        ),
    ]
