# Generated by Django 5.0.6 on 2024-10-02 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('checkin_date', models.DateField()),
                ('checkin_time', models.TimeField()),
                ('checkout_time', models.TimeField()),
                ('booking_status', models.CharField(choices=[('upcoming', 'Upcoming Bookings'), ('confirmed', 'Past Bookings'), ('cancelled', 'Cancelled Bookings')], default='upcoming', max_length=30)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.facility')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.student')),
            ],
        ),
    ]
