<<<<<<< HEAD
# Generated by Django 5.1.1 on 2024-09-23 11:34
=======
# Generated by Django 5.1.1 on 2024-09-27 14:52
>>>>>>> main

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('checkin_time', models.DateTimeField()),
                ('checkout_time', models.DateTimeField()),
                ('booking_status', models.CharField(max_length=20)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.facility')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.student')),
            ],
        ),
    ]
