# Generated by Django 5.0.6 on 2024-10-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='description',
        ),
    ]
